# Generated by Django 3.1.5 on 2021-01-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0004_auto_20210118_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='myawards.project'),
        ),
    ]
