# Generated by Django 3.1.5 on 2021-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0007_auto_20210121_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
