# Generated by Django 3.1.5 on 2021-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0008_auto_20210123_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
